### ISSUE TITLE
proposal: green for upvote/like button, red for downvote / dislike

### ISSUE THREAD

**Issue by DanielRuf** [angular-schule/demo-buggy-book-rating#1]
Currently the upvote / like button is red which is not optimal in regards of UX and accessibility.

These should be logically red (downvote) and green (upvote).

**Comment by fmalcher** [comment]
Thanks 😄  We consider fixing this in our next Chrome DevTools talk.
It's just a demo app, so UX was in fact not the primary focus. 🙈 
However: PRs are welcome!

**Comment by DanielRuf** [comment]
Right =)

Maybe we can cooperate in the future and we from Hackerstolz can interest more people for such great talks and handson examples at some sort of hackathon ;-)

**Comment by JohannesHoppe** [comment]
Yeah. Sounds cool, I live next to Mannheim. Are you only interested in workshops or is a talk also fine?

**Comment by DanielRuf** [comment]
Both are interesting. We organize also Frontend Rhein Neckar and we could meed some related talks ;-)

**Comment by DanielRuf** [comment]
Both are interesting for us. =)

We also organize also Frontend Rhein Neckar and we could meed some related talks ;-)
